# Generated by Django 3.0.6 on 2023-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230524_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/categorias/img_defecto.jpg', upload_to='uploads/categorias/', verbose_name='Imagen de categoria'),
        ),
    ]
